//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

pub mod prelude;

pub mod circuits;
pub mod constructor_results;
pub mod constructor_standings;
pub mod constructors;
pub mod driver_standings;
pub mod drivers;
pub mod lap_times;
pub mod pit_stops;
pub mod qualifying;
pub mod races;
pub mod results;
pub mod seasons;
pub mod sprint_results;
pub mod status;

seaography::register_entity_modules!([
    circuits,
    constructor_results,
    constructor_standings,
    constructors,
    driver_standings,
    drivers,
    lap_times,
    pit_stops,
    qualifying,
    races,
    results,
    seasons,
    sprint_results,
    status,
]);
