//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;

#[sea_orm::model]
#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel)]
#[sea_orm(table_name = "qualifying")]
pub struct Model {
    #[sea_orm(column_name = "qualifyId", primary_key)]
    pub qualify_id: i32,
    #[sea_orm(column_name = "raceId")]
    pub race_id: i32,
    #[sea_orm(column_name = "driverId")]
    pub driver_id: i32,
    #[sea_orm(column_name = "constructorId")]
    pub constructor_id: i32,
    pub number: i32,
    pub position: Option<i32>,
    pub q1: Option<String>,
    pub q2: Option<String>,
    pub q3: Option<String>,
    #[sea_orm(
        belongs_to,
        from = "constructor_id",
        to = "constructor_id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    pub constructors: HasOne<super::constructors::Entity>,
    #[sea_orm(
        belongs_to,
        from = "driver_id",
        to = "driver_id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    pub drivers: HasOne<super::drivers::Entity>,
    #[sea_orm(
        belongs_to,
        from = "race_id",
        to = "race_id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    pub races: HasOne<super::races::Entity>,
}

impl ActiveModelBehavior for ActiveModel {}
