//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;

#[sea_orm::model]
#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel)]
#[sea_orm(table_name = "status")]
pub struct Model {
    #[sea_orm(column_name = "statusId", primary_key)]
    pub status_id: i32,
    pub status: String,
    #[sea_orm(has_many)]
    pub results: HasMany<super::results::Entity>,
    #[sea_orm(has_many)]
    pub sprint_results: HasMany<super::sprint_results::Entity>,
}

impl ActiveModelBehavior for ActiveModel {}
