//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;

#[sea_orm::model]
#[derive(Clone, Debug, PartialEq, DeriveEntityModel)]
#[sea_orm(table_name = "constructorStandings")]
pub struct Model {
    #[sea_orm(column_name = "constructorStandingsId", primary_key)]
    pub constructor_standings_id: i32,
    #[sea_orm(column_name = "raceId")]
    pub race_id: i32,
    #[sea_orm(column_name = "constructorId")]
    pub constructor_id: i32,
    #[sea_orm(column_type = "Float")]
    pub points: f32,
    pub position: Option<i32>,
    #[sea_orm(column_name = "positionText")]
    pub position_text: Option<String>,
    pub wins: i32,
    #[sea_orm(
        belongs_to,
        from = "constructor_id",
        to = "constructor_id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    pub constructors: HasOne<super::constructors::Entity>,
    #[sea_orm(
        belongs_to,
        from = "race_id",
        to = "race_id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    pub races: HasOne<super::races::Entity>,
}

impl ActiveModelBehavior for ActiveModel {}
