//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;

#[sea_orm::model]
#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel)]
#[sea_orm(table_name = "races")]
pub struct Model {
    #[sea_orm(column_name = "raceId", primary_key)]
    pub race_id: i32,
    pub year: i32,
    pub round: i32,
    #[sea_orm(column_name = "circuitId")]
    pub circuit_id: i32,
    pub name: String,
    pub date: Date,
    pub time: Option<Time>,
    #[sea_orm(unique)]
    pub url: Option<String>,
    pub fp1_date: Option<Date>,
    pub fp1_time: Option<Time>,
    pub fp2_date: Option<Date>,
    pub fp2_time: Option<Time>,
    pub fp3_date: Option<Date>,
    pub fp3_time: Option<Time>,
    pub quali_date: Option<Date>,
    pub quali_time: Option<Time>,
    pub sprint_date: Option<Date>,
    pub sprint_time: Option<Time>,
    #[sea_orm(
        belongs_to,
        from = "circuit_id",
        to = "circuit_id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    pub circuits: HasOne<super::circuits::Entity>,
    #[sea_orm(has_many)]
    pub constructor_results: HasMany<super::constructor_results::Entity>,
    #[sea_orm(has_many)]
    pub constructor_standings: HasMany<super::constructor_standings::Entity>,
    #[sea_orm(has_many)]
    pub driver_standings: HasMany<super::driver_standings::Entity>,
    #[sea_orm(has_many)]
    pub lap_times: HasMany<super::lap_times::Entity>,
    #[sea_orm(has_many)]
    pub pit_stops: HasMany<super::pit_stops::Entity>,
    #[sea_orm(has_many)]
    pub qualifyings: HasMany<super::qualifying::Entity>,
    #[sea_orm(has_many)]
    pub results: HasMany<super::results::Entity>,
    #[sea_orm(
        belongs_to,
        from = "year",
        to = "year",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    pub seasons: HasOne<super::seasons::Entity>,
    #[sea_orm(has_many)]
    pub sprint_results: HasMany<super::sprint_results::Entity>,
}

impl ActiveModelBehavior for ActiveModel {}
