//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;

#[sea_orm::model]
#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel)]
#[sea_orm(table_name = "seasons")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub year: i32,
    #[sea_orm(unique)]
    pub url: String,
    #[sea_orm(has_many)]
    pub races: HasMany<super::races::Entity>,
}

impl ActiveModelBehavior for ActiveModel {}
