//! `SeaORM` Entity. Generated by sea-orm-codegen 0.12.15

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel)]
#[sea_orm(table_name = "circuits")]
pub struct Model {
    #[sea_orm(column_name = "circuitId", primary_key)]
    pub circuit_id: i32,
    #[sea_orm(column_name = "circuitRef")]
    pub circuit_ref: String,
    pub name: String,
    pub location: Option<String>,
    pub country: Option<String>,
    #[sea_orm(column_type = "Float", nullable)]
    pub lat: Option<f32>,
    #[sea_orm(column_type = "Float", nullable)]
    pub lng: Option<f32>,
    pub alt: Option<i32>,
    #[sea_orm(unique)]
    pub url: String,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}

impl ActiveModelBehavior for ActiveModel {}
