//! `SeaORM` Entity. Generated by sea-orm-codegen 0.12.15

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "constructors")]
pub struct Model {
    #[sea_orm(column_name = "constructorId", primary_key)]
    pub constructor_id: i32,
    #[sea_orm(column_name = "constructorRef")]
    pub constructor_ref: String,
    #[sea_orm(unique)]
    pub name: String,
    pub nationality: Option<String>,
    pub url: String,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}

impl ActiveModelBehavior for ActiveModel {}
