//! `SeaORM` Entity. Generated by sea-orm-codegen 0.12.15

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "lapTimes")]
pub struct Model {
    #[sea_orm(column_name = "raceId", primary_key, auto_increment = false)]
    pub race_id: i32,
    #[sea_orm(column_name = "driverId", primary_key, auto_increment = false)]
    pub driver_id: i32,
    #[sea_orm(primary_key, auto_increment = false)]
    pub lap: i32,
    pub position: Option<i32>,
    pub time: Option<String>,
    pub milliseconds: Option<i32>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}

impl ActiveModelBehavior for ActiveModel {}
