//! `SeaORM` Entity. Generated by sea-orm-codegen 0.12.15

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "qualifying")]
pub struct Model {
    #[sea_orm(column_name = "qualifyId", primary_key)]
    pub qualify_id: i32,
    #[sea_orm(column_name = "raceId")]
    pub race_id: i32,
    #[sea_orm(column_name = "driverId")]
    pub driver_id: i32,
    #[sea_orm(column_name = "constructorId")]
    pub constructor_id: i32,
    pub number: i32,
    pub position: Option<i32>,
    pub q1: Option<String>,
    pub q2: Option<String>,
    pub q3: Option<String>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}

impl ActiveModelBehavior for ActiveModel {}
