//! `SeaORM` Entity. Generated by sea-orm-codegen 0.12.15

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "races")]
pub struct Model {
    #[sea_orm(column_name = "raceId", primary_key)]
    pub race_id: i32,
    pub year: i32,
    pub round: i32,
    #[sea_orm(column_name = "circuitId")]
    pub circuit_id: i32,
    pub name: String,
    pub date: Date,
    pub time: Option<Time>,
    #[sea_orm(unique)]
    pub url: Option<String>,
    pub fp1_date: Option<Date>,
    pub fp1_time: Option<Time>,
    pub fp2_date: Option<Date>,
    pub fp2_time: Option<Time>,
    pub fp3_date: Option<Date>,
    pub fp3_time: Option<Time>,
    pub quali_date: Option<Date>,
    pub quali_time: Option<Time>,
    pub sprint_date: Option<Date>,
    pub sprint_time: Option<Time>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}

impl ActiveModelBehavior for ActiveModel {}
